Allow void as statement
ni/javascript-styleguide pull request #51
Opened 2021-06-30 07:40 UTC by LukasKall

Allow `void` as statement to explicitly mark a promise as intentionally not awaited, as discussed in issue #43.

@rajsite I think we should publish a new minor release after this. It's not a breaking change, but it changes a rule to be less strict.

2021-07-14 17:25 UTC, mure approved these changes

2021-07-14 19:10 UTC, rajsite commented
@LukasKall it looks like this change includes package-lock changes which are unexpected. My guess is that you have npm@7 installed locally and running npm install resulted in updates to the lockfile to the npm7 format (aka v2). We should not include that change in this PR and explicitly require update to npm7.

Can you either remove the lockfile change in the PR or temporarily switch back to `npm i -g npm@6` for this PR?

2021-07-14 19:11 UTC, rajsite requested changes
lock file changes should not be included

2021-07-15 07:13 UTC, LukasKall commented
> @LukasKall it looks like this change includes package-lock changes which are unexpected. My guess is that you have npm@7 installed locally and running npm install resulted in updates to the lockfile to the npm7 format (aka v2). We should not include that change in this PR and explicitly require update to npm7 in a separate PR.
> 
> Can you either remove the lockfile change in the PR or temporarily switch back to `npm i -g npm@6` for this PR?

@rajsite  Sorry, my bad. I reverted the changes to the lockfile.

2021-07-20 23:07 UTC, rajsite approved these changes

2021-07-20 23:08 UTC, merged